### ISSUE TITLE
Font is incorrectly recognized as DejaVu Sans Mono with style = Book

### ISSUE THREAD

**Issue by SteliosPapamichail** [isaif/polybar-wifi-ramp-icons#1]
There seems to be something wrong with how the patched font is named because after following the instructions in the README file and installing it on the system, the font is recognized as `DejaVu Sans Mono:style=Book` which makes it difficult to use since the user may already be using another DejaVu Sans Mono font. 

For example, in my case I wanted to use this font with Polybar but since I have already installed another DejaVu Sans Mono font and due to them having the same name, Polybar fails to use it appropriately. 

Apart from the font's name after installation, the style is also wrong since it's not `wifi-ramp` but `Book` for some reason.

The installation was verified using `fc-list | grep -i "wifi"`. 

Here's the above command's output:

```
/home/steliosp/.local/share/fonts/DejaVuSansMono-wifi-ramp.ttf: DejaVu Sans Mono:style=Book
/home/steliosp/.fonts/DejaVuSansMono-wifi-ramp.ttf: DejaVu Sans Mono:style=Book
```

and [here is](https://ibb.co/tmg5RVC) an image showcasing the example issue with Polybar.

Thank you in advance for reading the issue!

**Comment by isaif** [comment]
Can you delete previously installed version of this file and then create a new folder in the fonts directory and then copy the font in that

**Comment by isaif** [comment]
Can you delete previously installed version of this font, create a new folder in the fonts directory and then copy the font in that directory.

The important step is to put the font in a new directory of its own inside the fonts directory. 

The other steps of installing being the same.

**Comment by SteliosPapamichail** [comment]
> Can you delete previously installed version of this font, create a new folder in the fonts directory and then copy the font in that directory.
> 
> The important step is to put the font in a new directory of its own inside the fonts directory. 
> 
> The other steps of installing being the same.

What should the folder name be? Is this a necessary step? If so, the ReadMe should probably be updated!

**Comment by isaif** [comment]
> What should the folder name be? Is this a necessary step? If so, the ReadMe should probably be updated!

Try making it unique, maybe `wifi-ramp`. I think this font is getting clubbed together with other fonts.

The ReadMe will be updated if required.

**Comment by JuanIgnacioHZ** [comment]
Hi, I found that if you change the font name in fontforge and export it to another file, the style changes and polybar is able to recognize the wifi icons.

Here's the font information of the file `DejaVuSansMono-wifi-ramp.ttf`, after changing it.
It is under Element->Font Info...

![ScreenshotFontforge](https://user-images.githubusercontent.com/69528931/148313162-3e8631f5-5ed3-4967-b4a4-0ff5fae0d17a.jpg)

Once the font is exported and installed, and fc-cache is run, ` fc-list | grep "Wifi"` outputs:
`/home/juan/.fonts/DejaVuSansMonoWifiRamp.ttf: DejaVu Sans Mono:style=WifiRamp`

And the icon shows up in polybar,
![ScreenshotIconPolybar](https://user-images.githubusercontent.com/69528931/148313381-d6572db9-cbaf-437e-87be-96b759ed56d4.jpg)
