### ISSUE TITLE
No unicode IDs?

### ISSUE THREAD

**Issue by JamarleyHub** [isaif/polybar-wifi-ramp-icons#2]
Been trying to find the respective Unicode-IDs for the characters for about an hour now and I honestly just give up.
Why, oh please for the love of god WHY would you not include the character IDs in your description?

**Comment by isaif** [comment]
It starts from U+e0d5 to U+e0d9 and U+e0da.

I just forgot to add it in readme 😅 
Thanks, I will update it soon.

**Comment by JamarleyHub** [comment]
Thanks for the fast reply.
I mean, without the IDs most of your work just kinda becomes useless which would be a shame. ^^'
